-- Phase 3A, PR A — additive migration. Adds real-user identity and
-- Magic Link auth foundation tables. Does NOT alter, drop, or rename
-- payment_events or entitlements (see server/sql/schema.sql) — Phase 2's
-- sandbox-test-user PoC path is completely untouched by this migration.
--
-- Run this once, after server/sql/schema.sql, against the same MariaDB
-- 10.5+ database used by Phase 2. This migration is NOT deployed to
-- Xserver as part of this PR.

CREATE TABLE IF NOT EXISTS users (
  -- UUIDv4, generated by server/src/Uuid.php. Public-facing identifier —
  -- never a sequential integer.
  id CHAR(36) NOT NULL,
  -- Lowercase + trim only. No Gmail dot/plus-alias folding — see the
  -- design spec's explicit note that any future alias-merging requires
  -- its own reviewed migration, not an automatic normalization change.
  email_normalized VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_email_normalized (email_normalized)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS magic_link_tokens (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  -- The pending identity a request-link call was issued for. NOT a FK
  -- to users at insert time — request-link.php never creates or looks
  -- up a users row.
  email_normalized VARCHAR(255) NOT NULL,
  -- Bound to the resolved user INSIDE the same transaction as the
  -- atomic token-consume + user find-or-create in
  -- MagicLinkAuthService::verify() — set only on successful
  -- verification, never at issue() time. ON DELETE SET NULL: if a user
  -- row were ever deleted (not implemented in this PR), the historical
  -- token record survives with its user link cleared.
  user_id CHAR(36) NULL,
  -- SHA-256 hex digest of the raw token. Raw token is NEVER stored.
  token_hash CHAR(64) NOT NULL,
  expires_at DATETIME NOT NULL,
  -- Set by the atomic conditional UPDATE in MagicLinkAuthService::
  -- verify() — enforces single-use. NULL means still valid/unused.
  used_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_token_hash (token_hash),
  KEY idx_email_normalized (email_normalized),
  KEY idx_user_id (user_id),
  CONSTRAINT fk_magic_link_tokens_user
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  -- SHA-256 hex digest of the raw session token. Raw token is NEVER
  -- stored. This is a real account credential — treated with the same
  -- care as the magic-link token.
  token_hash CHAR(64) NOT NULL,
  -- A session must always belong to a real user — NOT NULL, and
  -- ON DELETE CASCADE: if a user row were ever deleted, that user's
  -- sessions are deleted with it rather than becoming orphaned rows
  -- that could otherwise resolve to a nonexistent user.
  user_id CHAR(36) NOT NULL,
  expires_at DATETIME NOT NULL,
  revoked_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_token_hash (token_hash),
  KEY idx_user_id (user_id),
  CONSTRAINT fk_sessions_user
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rate_limits (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  -- 'magic_link_email' | 'magic_link_ip' — see server/src/Auth/RateLimiter.php.
  bucket VARCHAR(32) NOT NULL,
  -- HMAC-SHA256(bucket:value, RATE_LIMIT_PEPPER) hex digest. NEVER the
  -- raw normalized email or raw IP address.
  identifier VARCHAR(128) NOT NULL,
  window_start DATETIME NOT NULL,
  count INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_bucket_identifier (bucket, identifier)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
