// Fetches hiragana stroke-order path data from the KanjiVG project
// (https://kanjivg.tagaini.net) for every character in CHARACTERS, and
// writes it to src/data/strokes.ts for the stroke-order animation (see
// components/StrokeOrderAnimation.tsx). Run once (whenever the character
// set changes):
//   npx tsx scripts/fetchStrokeData.ts
import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import { CHARACTERS } from '../src/data/characters'

const KANJIVG_BASE_URL = 'https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji'
const OUT_FILE = path.resolve(import.meta.dirname, '../src/data/strokes.ts')

async function fetchStrokes(kana: string): Promise<string[]> {
  const hex = kana.codePointAt(0)!.toString(16).padStart(5, '0')
  const res = await fetch(`${KANJIVG_BASE_URL}/${hex}.svg`)
  if (!res.ok) throw new Error(`KanjiVG fetch failed (${res.status}) for "${kana}" (${hex})`)
  const svg = await res.text()
  const pathMatches = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)]
  if (pathMatches.length === 0) throw new Error(`No stroke paths found for "${kana}" (${hex})`)
  return pathMatches.map((m) => m[1])
}

async function main() {
  console.log('Fetching stroke data from KanjiVG...')
  const entries: [string, string[]][] = []
  for (const char of CHARACTERS) {
    const strokes = await fetchStrokes(char.kana)
    entries.push([char.id, strokes])
    console.log(`  ${char.id} (${char.kana}): ${strokes.length} strokes`)
  }

  const body = entries
    .map(([id, strokes]) => `  ${id}: [${strokes.map((s) => JSON.stringify(s)).join(', ')}],`)
    .join('\n')

  const content = `// Hiragana stroke-order path data, sourced from the KanjiVG project
// (https://kanjivg.tagaini.net), Copyright (C) 2009/2010/2011 Ulrich Apel,
// licensed under CC BY-SA 3.0 (https://creativecommons.org/licenses/by-sa/3.0/).
// This file is a derivative of that data (stroke paths only, re-keyed to
// this app's character ids) and is itself licensed under CC BY-SA 3.0 — see
// scripts/fetchStrokeData.ts for provenance and src/routes/AboutPage.tsx for
// the on-app credit. Generated by scripts/fetchStrokeData.ts — do not
// hand-edit; re-run the script instead.
//
// Each entry is an ordered list of SVG path \`d\` strings (viewBox "0 0 109
// 109", KanjiVG's standard canvas) — one per stroke, in writing order.
export const STROKE_PATHS: Record<string, string[]> = {
${body}
}
`

  await writeFile(OUT_FILE, content)
  console.log(`\nWrote ${entries.length} characters to ${path.relative(process.cwd(), OUT_FILE)}`)
}

main()
