// Pre-generates つくよみちゃん (COEIROINK) audio for every WORD in the
// curriculum, so the deployed app can ship static audio files instead of
// depending on a locally-running COEIROINK engine at playback time. Run once
// (whenever the word list changes) with a local COEIROINK v2 engine running
// on the default port:
//   npx tsx scripts/generateAudio.ts
//
// Character audio (public/audio/characters/) is NOT generated by this
// script — isolated single-mora synthesis came out weak on COEIROINK (and
// on VOICEVOX-family engines generally, since they're tuned for continuous
// running speech, not bare morae). Those clips are real human recordings
// checked directly into public/audio/characters/; do not overwrite them
// with this script.
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { ALL_WORDS } from '../src/data/words'

const COEIROINK_BASE_URL = 'http://localhost:50032'
const COEIROINK_SPEAKER_UUID = '3c37646f-3881-5374-2a83-149267990abc' // つくよみちゃん
const COEIROINK_STYLE_ID = 0 // れいせい (calm)
const OUT_DIR = path.resolve(import.meta.dirname, '../public/audio')

// Words where COEIROINK's automatic prosody estimation gets the pitch
// accent wrong — confirmed against accentjiten.com's aggregated accent
// dataset (NHK/OJAD/Wiktionary/Wadoku/Kanjium), not just guessed from
// memory (an earlier pass here that relied on memory got several of these
// backwards — see 2026-08-10 correction). Registering these via
// /v1/set_dictionary is IN-MEMORY ONLY on the running engine, so it has to
// be redone on every engine restart — doing it here means every
// regeneration run reapplies the fix automatically instead of silently
// reverting to the broken auto-estimate.
//
// `accent` is the accent nucleus position (0 = heiban/no drop, N = pitch
// drops after the Nth mora). Single-mora words (て/hand) can't be corrected
// this way — COEIROINK always renders an isolated 1-mora word the same way
// regardless of the registered accent, so it's left out here.
const ACCENT_OVERRIDES = [
  { word: 'まど', yomi: 'マド', accent: 1, numMoras: 2 }, // was two flat 1-mora phrases; 窓 is atamadaka
  { word: 'なまえ', yomi: 'ナマエ', accent: 0, numMoras: 3 }, // was mis-split as なま(atamadaka) + え; 名前 is heiban
  { word: 'みそしる', yomi: 'ミソシル', accent: 3, numMoras: 4 }, // was mis-split as みそ + しる (two phrases)
  { word: 'とんかつ', yomi: 'トンカツ', accent: 0, numMoras: 4 }, // was mis-split as とん + かつ (two phrases)
  { word: 'いえ', yomi: 'イエ', accent: 0, numMoras: 2 }, // was atamadaka; 家 is heiban
  { word: 'あか', yomi: 'アカ', accent: 1, numMoras: 2 }, // 赤 is atamadaka (already correct by default; pinned)
  { word: 'あさ', yomi: 'アサ', accent: 1, numMoras: 2 }, // 朝 is atamadaka (already correct by default; pinned)
  { word: 'えき', yomi: 'エキ', accent: 1, numMoras: 2 }, // 駅 is atamadaka (already correct by default; pinned)
  { word: 'うえ', yomi: 'ウエ', accent: 0, numMoras: 2 }, // was atamadaka; 上 is heiban
  { word: 'かう', yomi: 'カウ', accent: 0, numMoras: 2 }, // was atamadaka; 買う is heiban
  { word: 'さけ', yomi: 'サケ', accent: 0, numMoras: 2 }, // was atamadaka; 酒 is heiban
  { word: 'なつ', yomi: 'ナツ', accent: 0, numMoras: 2 }, // was atamadaka; 夏 is heiban
  { word: 'みず', yomi: 'ミズ', accent: 0, numMoras: 2 }, // was atamadaka; 水 is heiban
  { word: 'あめ', yomi: 'アメ', accent: 1, numMoras: 2 }, // was heiban (matched 飴/candy); 雨 is atamadaka
  { word: 'とり', yomi: 'トリ', accent: 0, numMoras: 2 }, // was atamadaka; 鳥 is heiban
  { word: 'よる', yomi: 'ヨル', accent: 1, numMoras: 2 }, // was heiban (matched the verb 因る/寄る); 夜 is atamadaka
]

async function applyAccentOverrides(): Promise<void> {
  const res = await fetch(`${COEIROINK_BASE_URL}/v1/set_dictionary`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ dictionaryWords: ACCENT_OVERRIDES }),
  })
  if (!res.ok) throw new Error(`set_dictionary failed (${res.status}): ${await res.text()}`)
}

async function synthesize(text: string): Promise<Buffer> {
  const res = await fetch(`${COEIROINK_BASE_URL}/v1/synthesis`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      speakerUuid: COEIROINK_SPEAKER_UUID,
      styleId: COEIROINK_STYLE_ID,
      text,
      speedScale: 1.0,
      volumeScale: 1.0,
      pitchScale: 0.0,
      intonationScale: 1.0,
      prePhonemeLength: 0.1,
      postPhonemeLength: 0.1,
      outputSamplingRate: 24000,
    }),
  })
  if (!res.ok) throw new Error(`synthesis failed (${res.status}) for "${text}": ${await res.text()}`)
  return Buffer.from(await res.arrayBuffer())
}

async function generateAll(subdir: string, items: { id: string; text: string }[]) {
  const dir = path.join(OUT_DIR, subdir)
  await mkdir(dir, { recursive: true })
  for (const { id, text } of items) {
    const wav = await synthesize(text)
    await writeFile(path.join(dir, `${id}.wav`), wav)
    console.log(`  ${subdir}/${id}.wav  ("${text}")`)
  }
}

async function main() {
  const speakersRes = await fetch(`${COEIROINK_BASE_URL}/v1/speakers`).catch(() => null)
  if (!speakersRes?.ok) {
    console.error('COEIROINK engine is not reachable at ' + COEIROINK_BASE_URL)
    console.error('Start the COEIROINK app first, then re-run this script.')
    process.exit(1)
  }

  await applyAccentOverrides()

  console.log('Generating word audio...')
  await generateAll(
    'words',
    ALL_WORDS.map((w) => ({ id: w.id, text: w.audioText ?? w.kana })),
  )

  console.log('Done.')
}

main()
