name: Server Unit Tests

on:
  pull_request:
    paths:
      - 'server/**'
      - '.github/workflows/server-unit-tests.yml'
  push:
    branches: [main]
    paths:
      - 'server/**'
      - '.github/workflows/server-unit-tests.yml'

permissions:
  contents: read

jobs:
  server-unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: '8.4'
          extensions: pdo_sqlite, sqlite3
      - run: php server/tests/run-tests.php
